### ISSUE TITLE
This seems to work with 3.4?

### ISSUE THREAD

**Issue by robertlagrant** [jerrykan/wsgi-liveserver#1]
Worth making it official on Pypi?

**Comment by jerrykan** [comment]
Sure, I haven't tried it with python3, but I don't see any reason why it shouldn't be tagged as working with it if there aren't any problems.

When I have a bit of time in the next few days I'll have a closer look at pushing a new release to PyPI.

**Comment by jerrykan** [comment]
A new version is now available on PyPI, including some minor fixes for Python3:

  https://pypi.python.org/pypi/wsgi-liveserver/0.3

Thanks for reporting the issue.

**Comment by robertlagrant** [comment]
Thanks!
